### ISSUE TITLE
Would you please add .idea to .gitignore?

### ISSUE THREAD

**Issue by lovepoem** [dubbo/intellij-idea-plugin#2]
Would you please add .idea to .gitignore?

**Comment by gejun123456** [comment]
https://stackoverflow.com/questions/11968531/what-to-gitignore-from-the-idea-folder

after checked, i should ignore the datasource folder and datasource.xml in idea folder.

i will make a pull request for that.

Thanks

**Comment by gejun123456** [comment]
fixed, thanks for advice.
